parameters:
  beute_wachstumsrate: 1.5
  raeuber_interaktionsrate: 0.1
  raeuber_todesrate: 0.1
  raeuber_vermehrungsrate: 0.01
  nahrung_wachstumsrate: 0.5
  nahrung_interaktionsrate: 0.05

initial_conditions:
  start_beute: 10
  start_raeuber: 5
  start_nahrung: 20

simulation:
  startzeit: 0
  endzeit: 100
  zeitschritt: 0.01
