# Simulation parameters
INITIAL_SIM_RATE = 100
MIN_SIM_RATE = 1
MAX_SIM_RATE = 150
RATE_STEP_SLIDER = 1

INITIAL_ELASTICITY = 1
MIN_ELASTICITY = 0.1
MAX_ELASTICITY = 1
ELASTICITY_STEP_SLIDER = 0.05

TIME_STEP = 0.005