beute_wachstumsrate: 0.432
raeuber_rate: 0.0189
raeuber_todesrate: 0.432
raeuber_effizienz: 0.00945
nahrungs_wachstumsrate: 0.36
nahrungs_verbrauchsrate: 0.007875
zeit_schritt: 0.005
anzahl_schritte: 30000
beute_population: 50
raeuber_population: 30
nahrungs_verfuegbarkeit: 100
